### ISSUE TITLE
change characters in MortalKombat?

### ISSUE THREAD

**Issue by ivan-v-kush** [nadavbh12/gym-rle#5]
Is it possible to change characters? By default are Scorpion and Jonny  Cage

**Comment by nadavbh12** [comment]
It is possible to change the characters when using the RLE python interface directly.
You can change it by calling`rle.setString("MK_player1_character")`
You can see different game specific options [here](https://github.com/nadavbh12/Retro-Learning-Environment/blob/master/src/environment/Settings.cxx#L334)

We haven't exposed this interface through gym-rle. So you'll have to work around it.
Maybe by `env.rle.setString("..."`
